version: '2'

services:
  # virtaul stack app ↓

  virtualstack-db:
    container_name: vs-db
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: virtualstack
      POSTGRES_USER: virtualstack
      POSTGRES_PASSWORD: virtualstack
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/virtualstack-db:/var/lib/postgresql/data
    restart: always

  gitbucket:
    container_name: vs-gitbucket
    image: shomatan/gitbucket:4.13-alpine
    environment:
      GITBUCKET_PORT: 80
      GITBUCKET_DB_HOST: gitbucket-db
    ports:
      - "8081:80"
      - "29418:29418"
    expose:
      - 80
    volumes:
      - ./volumes/gitbucket/repositories:/gitbucket/repositories
      - ./volumes/gitbucket/data:/gitbucket/data
    restart: always

  gitbucket-db:
    container_name: vs-postgres
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: gitbucket
      POSTGRES_USER: gitbucket
      POSTGRES_PASSWORD: gitbucket
    volumes:
      - ./volumes/gitbucket-db:/var/lib/postgresql/data
    restart: always

  jenkins:
    container_name: vs-jenkins
    image: jenkins:2.46.3
    ports:
      - "8082:8080"
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
    restart: always

  docker:
    container_name: vs-docker
    image: docker:17.05-dind
    privileged: true
    restart: always

  registry:
    container_name: vs-registry
    image: registry:2.6.1
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/registry:/var/lib/registry
    restart: always